In [1]:
import pandas as pd
import numpy as np
utility_matrix = pd.read_csv("50%_utility_matrix.csv")
feature_matrix = pd.read_csv("feature_matrix.csv")

In [ ]:
def getRatingVectorOfNthUser(n:int):
    #get the rating vector of n-th user and the min and max anime_id
    column_n = str(n)
    rating = utility_matrix[[column_n]].values

    #normalize the rating value
    return rating

print(getRatingVectorOfNthUser(1))

In [17]:
def similarity(u1:int,u2:int) -> float:
    vector_u1 = getRatingVectorOfNthUser(u1)
    vector_u2 = getRatingVectorOfNthUser(u2)
    
    return ((vector_u1.T).dot(vector_u2))/((np.linalg.norm(vector_u1))*np.linalg.norm(vector_u2))

print(similarity(1,10)[0][0])

0.216788524485329


In [22]:
similar_matrix = [[0 for i in range(3000)] for j in range(3000)]
print(np.array(similar_matrix))
for i in range(len(similar_matrix)):
    for j in range(len(similar_matrix)):
        if i == j:
            similar_matrix[i][j] = 1
        if similar_matrix[j][i] != 0:
            similar_matrix[i][j] = similar_matrix[j][i]
        else:
            similar_matrix[i][j] = similarity(i+1,j+1)[0][0]
print(np.array(similar_matrix))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[ 1.         -0.04225847  0.01613407 ...  0.12020174 -0.06485681
  -0.04684624]
 [-0.04225847  1.          0.13368172 ...  0.          0.
  -0.10868281]
 [ 0.01613407  0.13368172  1.         ...  0.11821869  0.13266331
  -0.13041145]
 ...
 [ 0.12020174  0.          0.11821869 ...  1.          0.15582341
  -0.11097402]
 [-0.06485681  0.          0.13266331 ...  0.15582341  1.
  -0.16842199]
 [-0.04684624 -0.10868281 -0.13041145 ... -0.11097402 -0.16842199
   1.        ]]


In [2]:
user = 1
max_similarity = 0
list_of_max = []
for i in range(2,36758):
    if similarity(user,i)[0][0] > max_similarity:
        max_similarity = similarity(user,i)[0][0]
        list_of_max.append((i,max_similarity))
print(list_of_max[:-4])

NameError: name 'similarity' is not defined